---
- name: "Directory Exists | {{ mariadb_runtime_root }}"
  file:
    state: directory
    path: "{{ mariadb_runtime_root }}"
    owner: "{{ mariadb_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - mariadb

- name: Configure | mariadb | pidfile
  lineinfile:
    state: present
    dest: /etc/mysql/my.cnf
    regexp: '^.*pid-file'
    line: "pid-file = {{ mariadb_pidfile_path }}"
  notify: Reload Service | mariadb
  tags:
    - pidfile
    - service
