---
- name: Configure | mariadb | pidfile
  lineinfile:
    state: present
    dest: /etc/mysql/my.cnf
    regexp: '^.*pid-file'
    line: "pid-file = {{ mariadb_pidfile_path }}"
  notify: Reload Service | mariadb
  tags:
    - pidfile
    - service
